INSERT INTO item_types(id, type_name, material, description) VALUES (1, 'Shirts', 'cotton', 'some sort of description for particular type. probably tags')
INSERT INTO item_types(id, type_name, material, description) VALUES (2, 'Sweaters', 'cotton', 'some sort of description for particular type. probably tags')
INSERT INTO item_types(id, type_name, material, description) VALUES (3, 'Pants', 'jeans', 'some sort of description for particular type. probably tags')
INSERT INTO item_types(id, type_name, material, description) VALUES (4, 'Hats', 'synthetic', 'some sort of description for particular type. probably tags')
INSERT INTO item_types(id, type_name, material, description) VALUES (5, 'Shoes', 'rubber', 'some sort of description for particular type. probably tags')

INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Adidas red shirt',1, 5, 1999, 'Random description for shirt type item')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Adidas blue shirt',1, 5, 1999, 'Random description for shirt type item')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Nike sports shirt',1, 5, 2499, 'Random description for shirt type item')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Nike green shirt',1, 5, 2499, 'Random description for shirt type item')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Daewoo super shirt',1, 5, 3999, 'Random description for shirt type item')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Uber T-shirt',1, 5, 3399, 'Random description for shirt type item')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Uber T-shirt',1, 5, 3399, 'Random description for shirt type item')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Uber T-shirt',1, 5, 3399, 'Random description for shirt type item')


INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Adidas black hoodie',2, 5, 6999, 'Random description for sweater type item')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Adidas white hoodie',2, 5, 5999, 'Random description for sweater type item')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Puma hoodie no-sleeves',2, 5, 5999, 'Random description for sweater type item')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Nike black hoodie',2, 5, 5999, 'Random description for sweater type item')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Nike white hoodie',2, 5, 5999, 'Random description for sweater type item')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Daewoo techinal hoodie',2, 5, 5999, 'Random description for sweater type item')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Daewoo techinal hoodie',2, 5, 5999, 'Random description for sweater type item')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Daewoo techinal hoodie',2, 5, 5999, 'Random description for sweater type item')

INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Blue jeans',3, 5, 2999, 'Random description for pants type item')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Black jeans',3, 5, 3499, 'Random description for pants type item')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('White jeans',3, 5, 1799, 'Random description for pants type item')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Cotton white pants',3, 5, 2399, 'Random description for pants type item')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Sport pants',3, 5, 3499, 'Random description for pants type item')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Cotton black pants',3, 5, 2899, 'Random description for pants type item')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Cotton black pants',3, 5, 2899, 'Random description for pants type item')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Cotton black pants',3, 5, 2899, 'Random description for pants type item')


INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Akubra',4, 5, 1299, 'Random description for hats items')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Baseball cap',4, 5, 699, 'Random description for hats items')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Bucker hat',4, 5, 1499, 'Random description for hats items')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Gatsby',4, 5, 899, 'Random description for hats items')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Kalpak',4, 5, 799, 'Random description for hats items')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Sun hat',4, 5, 1099, 'Random description for hats items')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Sun hat',4, 5, 1099, 'Random description for hats items')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Sun hat',4, 5, 1099, 'Random description for hats items')



INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Trainers',5, 5, 3499, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Uggs',5, 5, 2999, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Work boots',5, 5, 4999, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Army boots',5, 5, 4599, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Platform pumps',5, 5, 2999, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('High heels',5, 5, 3399, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Trainers',5, 5, 3499, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Uggs',5, 5, 2999, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Work boots',5, 5, 4999, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Army boots',5, 5, 4599, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Platform pumps',5, 5, 2999, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('High heels',5, 5, 3399, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Trainers',5, 5, 3499, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Uggs',5, 5, 2999, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Work boots',5, 5, 4999, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Army boots',5, 5, 4599, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Platform pumps',5, 5, 2999, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('High heels',5, 5, 3399, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Trainers',5, 5, 3499, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Uggs',5, 5, 2999, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Work boots',5, 5, 4999, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Army boots',5, 5, 4599, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Platform pumps',5, 5, 2999, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('High heels',5, 5, 3399, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Trainers',5, 5, 3499, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Uggs',5, 5, 2999, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Work boots',5, 5, 4999, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Army boots',5, 5, 4599, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Platform pumps',5, 5, 2999, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('High heels',5, 5, 3399, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Trainers',5, 5, 3499, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Uggs',5, 5, 2999, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Work boots',5, 5, 4999, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Army boots',5, 5, 4599, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Platform pumps',5, 5, 2999, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('High heels',5, 5, 3399, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Trainers',5, 5, 3499, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Uggs',5, 5, 2999, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Work boots',5, 5, 4999, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Army boots',5, 5, 4599, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('Platform pumps',5, 5, 2999, 'Random description for shoes')
INSERT INTO items_all (itemName, itemType_id, qty, price, description) VALUES('High heels',5, 5, 3399, 'Random description for shoes')




